### PR TITLE
android 14 compatible, remove jcenter, publish using maven-publish, ksp... and more

### PR DESCRIPTION
**Pull request by helloimfrog**
Hi, I have added some changes and I hope they will make this dependency live with us longer and longer 😁
- `registerReceiver` with `ContextCompat`, added RECEIVER_EXPORTED, RECEIVER_NOT_EXPORTED to make things work with Android 14 (SDK 34)
- Target SDK 34, min SDK 16, AGP 8.2.0, Gradle 8.5, Kotlin 1.9.20
- Publish with `maven-publish` (steps have been noted on README.MD)
- Removed `jcenter()`
- Upgraded all dependencies to latest version (at the time I wrote these boring notes 🥺)
- Migrated from `kapt` to `ksp`
- Bump version to 3.2.1

### CODE REVIEW

**Comment by kesha-antonov** [comment]
Hi

Did you upload your code to maven or elsewhere so we could try to use it?

I need somehow to add it to my lib to try https://github.com/kesha-antonov/react-native-background-downloader/blob/master/android/build.gradle#L30

**Comment by Kutikov** [comment]
Same question: how can I update my app's dependencies to use your version of androidx library (3.2.1)?

**Comment by amrashraf1992** [comment]
> Same question: how can I update my app's dependencies to use your version of androidx library (3.2.1)?

SAME Question for me??

**Comment by Kutikov** [comment]
Try it out: new prereleases using the code of @helloimfrog from this pull request

_**Please give me any feedback!**_

https://github.com/Kutikov/fetch2-android/releases/tag/3.2.1-android14

**Comment by LunevNF** [comment]
@Kutikov огонь!

**Comment by rovedashcam** [comment]
can you please android-14 which gradle dependencies we have to use

**Pull request merged**
