### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by AlexStarc**
- Added some methods which seems to be helpful
- Added some logging to database code
- Corrected some kotlin code-style

### CODE REVIEW

**Comment by AlexStarc** [comment]
Seems integration check has been failed due to some travis issue

**Comment by tonyofrancis** [comment]
@AlexStarc Will have a deeper look over the weekend before I merge. But so far looks good.

**Comment by AlexStarc** [comment]
I would appreciate any suggestions and ready to update if any comments.

**Comment by tonyofrancis** [comment]
@AlexStarc I will try to get to this today. Been super busy lately. Sorry for the delay.

**Pull request merged**
