### PR TITLE
Makes checksum check more flexible

### PR DESCRIPTION
**Pull request by akurni**
I added new method called getContentHash() to enable custom implementation of getting file hash from the server. I also modified most MD5 method to Hash to generalise the method, since not all checksum is using MD5 hash. I didn't touch the database yet, since I want to have your approval first @tonyofrancis . Thanks

### CODE REVIEW

**Comment by tonyofrancis** [comment]
@akurni took a quick look and looks good so far. Want to take a second look when I have more time

**Comment by tonyofrancis** [comment]
@akurni was not able to get to this over the weekend. But will try to today.

**Comment by akurni** [comment]
No problem

**Comment by tonyofrancis** [comment]
@akurni Merged!!

**Pull request merged**
