### PR TITLE
last changes from 3.0.12/3.1.6 with sdk-34-fix-registerReceiver

### PR DESCRIPTION
**Pull request by Kutikov**
Upstream all the latest changes from @tonyofrancis and @thib-rdr into a single fork with fixes of register receiver (Android SDK 34) from [Nguyen Ngoc Long](https://github.com/helloimfrog) (PR #665 ). 

- Min SDK version - 16, 
- Max SDK version - 34
- OkHttp version - 3.12

### CODE REVIEW

**Comment by Kutikov** [comment]
For everyone who wants to test by himself download [prebuild *.aar](https://github.com/Kutikov/fetch2-android/releases/tag/3.2.2-android14). **Give me any feedback, please!**

**Comment by PVoLan** [comment]
@Kutikov Thanks, man, you've saved my day. Applied your v3.2.2 aars instead of 3.1.6 in my project, works fine as far as I see

**Comment by vicajilau** [comment]
It's awesome @Kutikov!! The only thing is I cannot download it adding the next in my gradle:

`implementation("com.github.Kutikov:fetch2-android:3.2.2-android14")  `

The reason is because it's failing on JitPack:

image

**Comment by Kutikov** [comment]
> It's awesome @Kutikov!! The only thing is I cannot download it adding the next in my gradle:
> 
> `implementation("com.github.Kutikov:fetch2-android:3.2.2-android14")  `
> 
> The reason is because it's failing on JitPack:
> 
> image
> 

Sorry for that, I'll try to load it to jitpack soon

**Comment by MdAbubakar** [comment]
@Kutikov please upload it to jitpack I'm in really need this one

**Comment by daniJimen** [comment]
Hi everyone @Kutikov , the version 3.2.2 its failing because it needs an extra import that not appears in the aar that its the room implementation; with that its working fine:
 implementation ("androidx.room:room-runtime:2.6.1")
 annotationProcessor ("androidx.room:room-compiler:2.6.1")
 androidTestImplementation ("androidx.room:room-testing:2.6.1")

**Comment by Kutikov** [comment]
When I'll have electricity and network, I'll add room dependencies and upload it to jitpack. I don't know when, war, you know, is not predictable thing

**Comment by Akaizz** [comment]
You guys can try:

`implementation("com.github.Akaizz.Fetch:fetch2:3.3") `

Hope this helps!

**Comment by krishnaviroja** [comment]
> It's awesome @Kutikov!! The only thing is I cannot download it adding the next in my gradle:
> 
> `implementation("com.github.Kutikov:fetch2-android:3.2.2-android14") `
> 
> The reason is because it's failing on JitPack:
> 
> image

Have you able to fix your's? As i am facing the same issue related to SDK 34

**Comment by krishnaviroja** [comment]
> When I'll have electricity and network, I'll add room dependencies and upload it to jitpack. I don't know when, war, you know, is not predictable thing

Are you able to upload?

**Comment by Kutikov** [comment]
> > When I'll have electricity and network, I'll add room dependencies and upload it to jitpack. I don't know when, war, you know, is not predictable thing
> 
> Are you able to upload?

No, I've tried, but no luck. If somebody can help me, let me know

**Pull request merged**
